URL_ADITYA = 'https://news.google.com/search?q=Aditya%20Birla%20Health%20Insurance%20Company&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_CARE = 'https://news.google.com/search?q=care%20health%20insurance%20company%20limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_MANIPAL = 'https://news.google.com/search?for=manipalcigna+health+insurance+company+limited+mumbai&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_NIVA = 'https://news.google.com/search?q=Niva%20Bupa%20Health%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_RELIANCE = 'https://news.google.com/search?q=Reliance%20Health%20Insurance%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_STAR = 'https://news.google.com/search?q=Star%20Health%20%26%20Allied%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_ACKO = 'https://news.google.com/search?q=Acko%20General%20Insurance%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_BAJAJ = 'https://news.google.com/search?q=Bajaj%20Allianz%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_CHOLA = 'https://news.google.com/search?q=Cholamandalam%20MS%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_FUTURE = 'https://news.google.com/search?q=Future%20Generali%20India%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_GO = 'https://news.google.com/search?q=Go%20Digit%20General%20Insurance%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_HDFC = 'https://news.google.com/search?q=HDFC%20Ergo%20General%20insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_ICICI = 'https://news.google.com/search?q=ICICI%20Lombard%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_IFFCO = 'https://news.google.com/search?q=FFCO%20Tokio%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Kotak = 'https://news.google.com/search?q=Kotak%20Mahindra%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Kshema = 'https://news.google.com/search?q=Kshema%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Liberty = 'https://news.google.com/search?q=Liberty%20General%20Insurance%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_National = 'https://news.google.com/search?q=Magma%20HDI%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Magma = 'https://news.google.com/search?q=National%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
# URL_NAVI = 'https://news.google.com/topics/CAAqLAgKIiZDQkFTRmdvTkwyY3ZNVEZtYUhGc01EZDZaQklGWlc0dFIwSW9BQVAB?hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Raheja = 'https://news.google.com/search?q=Raheja%20QBE%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Royal = 'https://news.google.com/search?q=Royal%20Sundaram%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Shriram = 'https://news.google.com/search?q=Shriram%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_SBI = 'https://news.google.com/search?q=SBI%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Tata = 'https://news.google.com/search?q=Tata%20AIG%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_The_New_India = 'https://news.google.com/search?q=The%20New%20India%20Assurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Oriental = 'https://news.google.com/search?q=The%20Oriental%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Universal = 'https://news.google.com/search?q=Universal%20Sompo%20General%20Insurance%20Company%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'
URL_Zuno = 'https://news.google.com/search?q=Zuno%20General%20Insurance%20Limited&hl=en-IN&gl=IN&ceid=IN%3Aen'

URLS = [URL_ADITYA, URL_CARE, URL_MANIPAL, URL_NIVA, URL_RELIANCE, URL_STAR, URL_ACKO, URL_BAJAJ, URL_CHOLA,
        URL_FUTURE, URL_GO, URL_HDFC, URL_ICICI, URL_IFFCO, URL_Kotak, URL_Kshema, URL_Liberty, URL_National,
        URL_Magma, URL_Raheja, URL_Royal, URL_Shriram, URL_SBI, URL_Tata, URL_The_New_India, URL_Oriental,
        URL_Universal, URL_Zuno]
